package com.akura.util;

public enum ModuleList {
    EMPLOYEE, USER, PRIVILAGE, DESIGNATION, USERPASSWORDCHANGE, CLAS, STUDENT, GRADE, SUBJECT, STUDENTSTATUS, GUARDIANTYPE, PLACEMENTTEST, SEMESTEREXAM, PLACEMENTTESTALLOCATIONANDPAYMENT,
    STUDENTCLAS, SEMESTEREXAMPAYMENT, CLASPAYMENT, RESULT
}
